---
openapi: 3.0.3
info:
  title: API сервиса для тестового задания
  version: 0.1.0
paths:
  "/api/v1/schools/{school_id}/classes":
    parameters:
    - name: school_id
      in: path
      example: 1
      required: true
      schema:
        type: integer
    get:
      summary: List classes
      tags:
      - Сlasses
      responses:
        '200':
          description: Список классов
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      "$ref": "#/components/schemas/Class"
  "/api/v1/schools":
    get:
      summary: List schools
      tags:
      - Schools
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      "$ref": "#/components/schemas/School"
  "/api/v1/schools/{school_id}/classes/{class_id}/students":
    parameters:
    - name: school_id
      in: path
      example: 1
      required: true
      schema:
        type: integer
    - name: class_id
      in: path
      example: 1
      required: true
      schema:
        type: integer
    get:
      summary: List students
      tags:
      - Students
      responses:
        '200':
          description: Список студентов
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      "$ref": "#/components/schemas/Student"
  "/api/v1/students":
    post:
      summary: Create student
      tags:
      - Students
      parameters: []
      responses:
        '201':
          description: Successful operation
          headers:
            X-Auth-Token:
              schema:
                type: string
              description: Токен для последующей авторизации
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Student"
        '405':
          description: Invalid input
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - first_name
              - last_name
              - surname
              - school_id
              - class_id
              properties:
                first_name:
                  type: string
                  example: Ivan
                last_name:
                  type: string
                  example: Ivanov
                surname:
                  type: string
                  example: Ivanovich
                school_id:
                  type: integer
                  example: 1
                class_id:
                  type: integer
                  example: 1
  "/api/v1/students/{user_id}":
    parameters:
    - name: user_id
      in: path
      example: 1
      required: true
      schema:
        type: integer
    delete:
      summary: Delete student
      tags:
      - Students
      security:
      - bearerAuth: []
      responses:
        '200':
          description: deleted
        '401':
          description: Некорректная авторизация
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      description: Ожидается токен, выдаваемый при регистрации студента
      bearerFormat: SHA256
  schemas:
    Student:
      type: object
      properties:
        id:
          type: integer
        first_name:
          type: string
        last_name:
          type: string
        surname:
          type: string
        school_id:
          type: integer
        class_id:
          type: integer
      required:
      - id
      - first_name
      - last_name
      - surname
      - school_id
      - class_id
    Class:
      type: object
      properties:
        id:
          type: integer
        number:
          type: integer
        letter:
          type: string
        students_count:
          type: integer
      required:
      - id
      - number
      - letter
      - students_count
    School:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
