default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: postgres
  pool: 5

development:
  <<: *default
  database: uchiru_development

test:
  <<: *default
  database: uchiru_test